### ISSUE TITLE
Learnings from my own efforts

### ISSUE THREAD

**Issue by jondot** [thoughtbot/react-native-template#17]
Hi!
Bumped into this repo while trying to solve templating react native apps for the nth time. I strongly believe in live templates (templates that are editable and runnable and then - a source for a generator).
I really like the cookiecutter approach but things like bundle id and java package names as expected are left out of the `bin/generate` script here. But if all these things would be covered in this script, then you'd end up implementing cookiecutter.

Currently i take the same approach sans cookiecutter. That is i have a special shazamish name, something odd, like `Froobanzle` and I have it in pascal case, snake case and shouting case for class name, variable name and bundle name and constant name, i will then globally replace that, sort of blindly too.

This approach makes a live project and a template project. It also withstood a bunch of ugly react-native upgrades. It also runs tests :)

I'm quite happy so far however i still hate the manual recursive renaming of folders (obviously cookiecutter solves), and i don't have the fancy 'pull the template from the internet' feature either.

Hope this helps!

**Comment by jakecraige** [comment]
Thanks for the recommendation! We're definitely still exploring how to handle having an example app that's runnable but also not more than you need to get started. 

We already feel the TemplateProject has more than what one might actually want to get started, that once they start the first thing is to remove/rename some files which isn't great. It does help in these early days for beginners to have some guidance though.

One thing that's nice about cookie cutter, which we don't use in this template yet is that it runs the files through a templating language so if we wanted to have things conditionally included/excluded we could (though we'd have to figure out how to keep the TemplateProject runnable and still have this).

Do you have an example of how you've set up your project? We'd love to see what we can takeaway from it to improve ours.

Going to close the issue since this is more of a discussion than issue, but thanks for opening it!
