### ISSUE TITLE
react-devtools?

### ISSUE THREAD

**Issue by croaky** [thoughtbot/react-native-template#24]
To `bin/setup`? Looks like it was recently patched to work with React Native https://blog.expo.io/using-react-devtools-with-react-native-6c59e636a03b

**Comment by jakecraige** [comment]
This could be cool if someone wants to try it out. If you use Atom + Nuclide it already has the inspector built in, this seems nice though for those who don't have that.

We would probably add it to the `package.json` rather than `bin/setup` since it's just a node module we don't need as a global thing

**Comment by purinkle** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [react-devtools?](https://trello.com/c/iB7XRJRI/15-react-devtools)
