### ISSUE TITLE
Integrate Flow / TypeScript

### ISSUE THREAD

**Issue by sharplet** [thoughtbot/react-native-template#8]

**Comment by jakecraige** [comment]
I'm pretty interested in this stuff. Just started using Flow on a client project this last week so I should have a good idea of some of it's capabilities and how to use it in not too long.

I did some reading up on Flow vs. TypeScript since they're so similar, I ended up choosing Flow primarily because it's just about automatically integrated into the RN tooling whereas TypeScript would require running yet another built process to transpile it down.

**Comment by purinkle** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Integrate Flow / TypeScript](https://trello.com/c/0flQE2By/12-integrate-flow-typescript)

**Comment by benfurber** [comment]
@jakecraige Is your transpile point about typescript still valid/important two years on?
